#!/usr/bin/env python3
"""Bridge T-41's on-disk backfill into the records (T-41 follow-up).

After `backfill-frontmatter.sh` updates a file's frontmatter, the
on-disk value is correct but the record's `frontmatter` BTreeMap
still holds the pre-backfill value. The next `omega-doc render` reads
the record, not the file, so the file gets reverted to the record's
old value.

This script reads the on-disk frontmatter for every managed
markdown, and updates the matching record's `frontmatter` map to
match. Run after `backfill-frontmatter.sh` (or as a final step
inside it).

Run from the repo root.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
RECORDS = REPO / "docs-data" / "records"

# Fields that are emitted at the top level of the record (not in
# the BTreeMap), so we do not need to copy them from the file.
TOP_LEVEL_FIELDS = {
    "status", "owner", "created", "updated", "version",
    # These are also generated by the renderer and would clobber
    # the canonical values if we copied them back from the file.
    "content_revision", "generation_id", "projection_version",
}

GENERATED_KEYS = TOP_LEVEL_FIELDS | {"source_doc_id"}


def fm_parse(text: str) -> dict[str, str]:
    """Parse a YAML-ish frontmatter block into a flat dict.

    We do not need a full YAML parser here — the project's frontmatter
    is a flat key: value block. Multi-line values are joined with their
    continuation indent.
    """
    m = re.search(r"^---\n(.*?)\n---\n", text, re.DOTALL | re.MULTILINE)
    if not m:
        return {}
    out: dict[str, str] = {}
    cur_key: str | None = None
    for line in m.group(1).split("\n"):
        if not line.strip():
            continue
        if line.startswith(" ") or line.startswith("\t"):
            if cur_key:
                out[cur_key] = out.get(cur_key, "") + "\n" + line
            continue
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        out[k.strip()] = v.strip().strip('"')
        cur_key = k.strip()
    return out


def main() -> int:
    # Build source_path -> (jsonl_path, record) index.
    by_path: dict[str, tuple[Path, dict]] = {}
    for jsonl in sorted(RECORDS.glob("*.jsonl")):
        with open(jsonl) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                sp = rec.get("source_path", "")
                if sp:
                    by_path[sp] = (jsonl, rec)

    updated = 0
    touched: dict[Path, list[dict]] = {}
    for d in ["docs/specs", "docs/decisions", "docs/prds", "docs/guide", "docs/whitepapers", "docs/archive"]:
        full = REPO / d
        if not full.is_dir():
            continue
        for f in sorted(full.iterdir()):
            if not f.name.endswith(".md"):
                continue
            sp = f.relative_to(REPO).as_posix()
            if sp not in by_path:
                continue
            text = f.read_text()
            file_fm = fm_parse(text)
            if not file_fm:
                continue
            jsonl, rec = by_path[sp]
            cur_fm = rec.setdefault("frontmatter", {})
            changed = False
            for k, v in file_fm.items():
                if k in GENERATED_KEYS:
                    continue
                if cur_fm.get(k) != v:
                    cur_fm[k] = v
                    changed = True
            if changed:
                updated += 1
                touched.setdefault(jsonl, []).append(rec)

    # Write back, preserving order. Use the mutated records from
    # by_path (which is a live dict) — do NOT re-read the file, that
    # would discard the mutations we just made.
    for jsonl in touched:
        sp_set = {sp for sp, (j, _) in by_path.items() if j == jsonl}
        with open(jsonl) as f:
            existing = [json.loads(line) for line in f if line.strip()]
        with open(jsonl, "w") as f:
            for r in existing:
                sp = r.get("source_path", "")
                if sp in by_path and by_path[sp][0] == jsonl:
                    # Use the mutated record from by_path.
                    f.write(json.dumps(by_path[sp][1], ensure_ascii=False) + "\n")
                else:
                    f.write(json.dumps(r, ensure_ascii=False) + "\n")

    print(f"updated {updated} record frontmatter maps")
    return 0


if __name__ == "__main__":
    sys.exit(main())
