[package]
name = "omega-doc-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "omega-doc"
path = "src/main.rs"

[dependencies]
omega-document = { path = "../omega-document" }
omega-project-layout = { path = "../omega-project-layout" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
omega-plan = { path = "../omega-plan" }
tempfile.workspace = true