[package]
name = "omega-hooks"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
libloading.workspace = true
omega-project-layout = { path = "../omega-project-layout" }
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[dev-dependencies]
omega-test-support = { path = "../omega-test-support" }