[package]
name = "omega-project"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
toml.workspace = true
omega-context = { path = "../omega-context" }
omega-plan = { path = "../omega-plan" }
omega-project-layout = { path = "../omega-project-layout" }